apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-project
  namespace: jenkins-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-project
  template:
    metadata:
      labels:
        app: jenkins-project
    spec:
      containers:
        - name: jenkins-project
          image: jubinraj/jenkins-project:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["jubin.py"]
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-project-service
  namespace: jenkins-cicd
spec:
  type: LoadBalancer
  selector:
    app: jenkins-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080